version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: $DOCKER_IMAGE
    docker:
      - image: $DOCKER_IMAGE
orbs:
  node: circleci/node@4.1


jobs:
  build_image:
    docker:
      - image: cimg/node:16.1.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: docker_build
          command: |
            time DOCKER_BUILDKIT=1 docker build -t $DOCKER_IMAGE .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $DOCKER_IMAGE
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  deploy_image:
    executor: docker-publisher
    docker:
      - image: cimg/node:16.1.0
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: login_docker
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: docker_push
          command: |
            docker push $DOCKER_IMAGE

workflows:
  version: 2.1
  build_n_deploy:
    jobs:
      - build_image:
          filters:
            branches:
              only: main
      - deploy_image:
          requires:
            - build_image
          filters:
            branches:
              only: main